### ISSUE TITLE
一行中最后一个字打错时无法察觉

### ISSUE THREAD

**Issue by nothingshiru** [KyleBing/typepad#21]
如图，行中最后一个字是“转”，而我打了“人”，此时因为这行字被顶上去了而导致这个错误无法被察觉。
![Screenshot_20211006_024505_com huawei browser](https://user-images.githubusercontent.com/79258245/136085326-5e60a7a1-cd54-44de-91f3-c32ca9a70d60.jpg)

**Comment by KyleBing** [comment]
已修复 v2.50
