### ISSUE TITLE
码长有略微的偏差

### ISSUE THREAD

**Issue by HaujetZhao** [KyleBing/typepad#24]
当跟打字数为 10 时，假设按了 36 个按键，那么码长就为「36 / 10 = 3.60」，只要按键数量不超过 100，小数点后第二位，一定恒为 0。

但实际上发文字数为 10 时，最后统计的码长在小数点第二位总是有数字，说明在计算的时候可能出了偏差，例如一个字没有算到总数，只以九个字进行计速，是这样吗？

**Comment by KyleBing** [comment]
看了下，最终的数值确实有问题，目前只计算到了结束前最后一次的正确字数。比如10个跟打正确，只算了9个正确。
中间过程中的计算是对的，只是最后一下是错误的，少算了一个字。

回头修正下，谢指正

**Comment by KyleBing** [comment]
原来是你  \(￣︶￣*\))

**Comment by KyleBing** [comment]
https://github.com/KyleBing/typepad/commit/d0000417b3de804873d62a3b70e348d216ce39f7
