### ISSUE TITLE
cet-4太好用了

### ISSUE THREAD

**Issue by iimuchen** [KyleBing/typepad#27]
作者大大，能不能添加添加六级和考研单词表呢

**Comment by KyleBing** [comment]
缺少词库资源

**Comment by KyleBing** [comment]
感谢认可，已添加更多词库。
![2022-03-29 174316](https://user-images.githubusercontent.com/12215982/160583468-66afc032-294a-421a-851f-b5ed81dec588.png)

**Comment by iimuchen** [comment]
感激不尽！之前用了几年的极速跟打器，今年方才发现您这个,给我的体验好过极速跟打，添雨。哈哈，总之非常感谢，劳您费心了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyleBing/typepad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyleBing/typepad] cet-4太好用了 (Issue #27)





 
感谢认可，已添加更多词库。

**Comment by KyleBing** [comment]
谢肯定
