### ISSUE TITLE
希望能增加中文词组乱序练习功能

### ISSUE THREAD

**Issue by carlwch** [KyleBing/typepad#28]
目前很多输入法存在简码打词组的特点，玫枫跟打器的文本练习类型有: 单字、文章、英文、单词和自定义，但自定义部分只能打单字或文章，希望可以增加自定义的中文词组练习模式，并可支持乱序练习。通过粘贴由空格或换行符隔开的词组文本，可以实现类似当前的单词练习功能。

**Comment by KyleBing** [comment]
不错的建议
- [ ] 添加词组支持

**Comment by KyleBing** [comment]
已添加词条练习模式，自定义时定义不同类型，日后再加。
