### ISSUE TITLE
tool-bar

### ISSUE THREAD

**Issue by mmdv** [KyleBing/typepad#3]
清晰，简洁，美观，非常好用，赞一个先。
发现一个小问题，输入文字后，tool-bar会产生大概一个像素的偏移。
比如 “0/15” 变为 “1/15”的时候 ，会分散码字注意力。
不知道后续会不会有小程序QAQ

**Comment by mmdv** [comment]
tool-bar

**Comment by mmdv** [comment]
清晰，简洁，美观，非常好用，赞一个先。
发现一个小问题，输入文字后，tool-bar会产生大概一个像素的偏移。
比如 “0/15” 变为 “1/15”的时候 ，会分散码字注意力。
不知道后续会不会有小程序QAQ

**Comment by KyleBing** [comment]
多谢赞赏，爱好这个，所以尽量把它做到最好。
对，这是个小问题，回头看看整整它。

小程序可以做，但应该不会有，这个需求没那么强烈，打字一般都是在电脑上打字，手机上打字无法捕捉按键信息，也没有多少必要性。
如果真想打，这个工具在手机端也是可以一用的。

**Comment by KyleBing** [comment]
fixed
