### ISSUE TITLE
能否出一个记录总跟打量的功能？

### ISSUE THREAD

**Issue by Lkmmaw** [KyleBing/typepad#38]
然后就是网页风格简洁，深得我心，感谢 😄🙏

**Comment by KyleBing** [comment]
谢认可，可能吧，那也得是加入用户功能之后了，短时间内没想法。不过倒是可以统计一下本地的数据。

**Comment by Lkmmaw** [comment]
本地就够了。对练习来说，练习量和练习时长的数据还是挺有意义的。
另外快捷键这里有点bug，像Cmd+Y有时会响应浏览器的历史记录，Ctrl+u、k也会响应Cmd的，能否给个开关呢？（我是Chrome+鼠须管）

**Comment by KyleBing** [comment]
目前，快捷键只在【输入框】内有用。

- [ ] 本地数据根据文章类别进行统计

**Comment by Lkmmaw** [comment]
是这样。主要是我在输入的时候会用Ctrl的快捷键，比如Ctrl+u清除编码……问题不大，感谢回复！

**Comment by KyleBing** [comment]
63f4c22d6154905358ac810c95db038a4b99f849
