### ISSUE TITLE
能否根据已经上屏的字来判断是否匹配

### ISSUE THREAD

**Issue by liubiantao** [KyleBing/typepad#4]
简洁好看，赞一个。这个好像不限制输入法吧，我试了用五笔和用小鹤音形效果是一样的。我准备拿它来练习小鹤音形。

不过有个问题，如下图，还没上屏的时候就总是出现红色的，看起来很烦。
![image](https://user-images.githubusercontent.com/3268218/86001555-9eea0980-ba41-11ea-831f-86452c6c08bc.png)

**Comment by KyleBing** [comment]
本来以为会比较麻烦，不可思议的解决了这个问题
