### ISSUE TITLE
希望添加历史打字记录一键全部清除按钮

### ISSUE THREAD

**Issue by cinvh** [KyleBing/typepad#40]
现在打字记录只能一条一条删除，上千条记录要一条一条的删，体验不好，希望可以一键清除

**Comment by KyleBing** [comment]
有的 
<img width="1029" alt="Screenshot 2022-11-09 at 21 52 48" src="https://user-images.githubusercontent.com/12215982/200847934-c69458ba-5f25-4685-9040-ef9ce5be8da4.png">
