### ISSUE TITLE
建议打字区文字全部删除时，记录的时间击键等数据初始化归零，然后重新打字时，再重新开始计时

### ISSUE THREAD

**Issue by cinvh** [KyleBing/typepad#44]
建议打字区文字全部删除时，记录的时间击键等数据初始化归零，然后重新打字时，再重新开始计时
![image](https://user-images.githubusercontent.com/32793181/201105107-a805d74b-c459-4c82-95d5-c26d77736c25.png)

**Comment by KyleBing** [comment]
重打可以用快捷键重载，保留这个空白时间还是有些意义的。
