### ISSUE TITLE
請問可以增加繁體的功能嗎？

### ISSUE THREAD

**Issue by nicohardmilk** [KyleBing/typepad#45]
你好，非常喜歡你的設計的工具，使用起來非常流輰且畫面簡潔，但在繁體打字使用上不是很方便尤其的常用字與文章的部分。請問可以做切換成繁體的功能嗎？
謝謝！
我是小白，不太會熟gitgub的環境，請見諒。

**Comment by KyleBing** [comment]
目前是没有繁体跟打文章的功能的，以后会添加自定义文章功能，到时候就可以打繁体了。
[https://github.com/KyleBing/typepad/issues/30](https://github.com/KyleBing/typepad/issues/30)

现在你可以下载离线文件，然后修改里面  `/js/class/Article.js` 里面的内容，替换成你需要的繁体文章，再双击  `index.html` 就能在本地使用了。

**Comment by nicohardmilk** [comment]
> 

好的。謝謝！
