### ISSUE TITLE
击键、码长统计数据可能有误

### ISSUE THREAD

**Issue by doloopo** [KyleBing/typepad#5]
![image](https://user-images.githubusercontent.com/39017669/87869577-78c9e080-c9d3-11ea-82ff-d7de97a62f50.png)

![image](https://user-images.githubusercontent.com/39017669/87869474-c42fbf00-c9d2-11ea-92b8-65046643585a.png)

两幅图中为本人所打的同一文段，且打字速度数据相近（127 字/分）。

添雨跟打器中测得的码长为 3.91，击键为 8.28；但在玫枫跟打器中测得的码长达到了 6.91，击键居然为惊人的 14.70，而本人在试验多种跟打器后也测出本人的击键不可能超过 10，即便有回退码长也不会达到 6.91，因此我认为玫枫跟打器的击键及码长的计算统计结果有误。

玫枫跟打器是很优秀的跟打器，谢谢你的付出！如果能修复我在上面提出的问题，相信此跟打器会变得更好！

**Comment by KyleBing** [comment]
嗯，那可能是里面算错了，我回头看看吧。暂时先只把速度作为参考吧。
