### ISSUE TITLE
macOS 13.6.1 Chrome 打不开网站

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [KyleBing/typepad#51]
Chrome升级到最新后：

<img width="755" alt="image" src="https://github.com/KyleBing/typepad/assets/22313057/86d2fe19-f821-43ed-9924-549d36488ae9">

平台为MBP14 M1Pro：

<img width="392" alt="image" src="https://github.com/KyleBing/typepad/assets/22313057/cac8e250-2f52-43e7-85fe-ff80478a05c2">

在Chrome中无法打开：

<img width="1471" alt="image" src="https://github.com/KyleBing/typepad/assets/22313057/f005bd3c-b4a8-4abe-9ac5-732c3f07ca20">

但在Safari中，即使报不安全，仍能打开：

<img width="1424" alt="image" src="https://github.com/KyleBing/typepad/assets/22313057/e07ac9f3-844b-4e26-a24c-97af46c79aa5">

是我这边有什么问题，还是谷歌又搞了什么妖蛾子？

**Comment by Lawrence-of-AnKing** [comment]
> Chrome升级到最新后：
> 
> <img alt="image" width="755" src="https://private-user-images.githubusercontent.com/22313057/309741108-86d2fe19-f821-43ed-9924-549d36488ae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTMxMjIsIm5iZiI6MTcwOTU1MjgyMiwicGF0aCI6Ii8yMjMxMzA1Ny8zMDk3NDExMDgtODZkMmZlMTktZjgyMS00M2VkLTk5MjQtNTQ5ZDM2NDg4YWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYWZjZTZlMmUwNjM3MTA4NjY5MWFkN2U0NTFiYjY5YTgwZGYxZDdiZGM4YzBhZDdkMGEzYWFkMjI4MTAyMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gC7smeiNWFRYZKY-uwc-Sd69nVIx4Va8X52zohBlWh8">
> 平台为MBP14 M1Pro：
> 
> <img alt="image" width="392" src="https://private-user-images.githubusercontent.com/22313057/309741217-cac8e250-2f52-43e7-85fe-ff80478a05c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTMxMjIsIm5iZiI6MTcwOTU1MjgyMiwicGF0aCI6Ii8yMjMxMzA1Ny8zMDk3NDEyMTctY2FjOGUyNTAtMmY1Mi00M2U3LTg1ZmUtZmY4MDQ3OGEwNWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZTY0YTE0YTg4M2ZjOTk3YTgwMWUyMjVmOTA5NTY4NTY2YTZiZGQ5N2U1YzdmMmQ5YWViM2ZiNzUxNjQ0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xa83fwbqGYEHL6_y4uQ2FBp4ha8OWaOW6lyvI9xRaao">
> 在Chrome中无法打开：
> 
> <img alt="image" width="1471" src="https://private-user-images.githubusercontent.com/22313057/309741361-f005bd3c-b4a8-4abe-9ac5-732c3f07ca20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTMxMjIsIm5iZiI6MTcwOTU1MjgyMiwicGF0aCI6Ii8yMjMxMzA1Ny8zMDk3NDEzNjEtZjAwNWJkM2MtYjRhOC00YWJlLTlhYzUtNzMyYzNmMDdjYTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMDRiNTdjNDE5ODk3N2Q5N2ZjNzA0ZmRlMDYxNTFmOWFkMWU0NTUyMTBkOTkxMjMxNjM1YmM0ZjJkOGM2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTVSWILiglWAjEssZli-NrTjj0CObe0g2eoZRtbEY30">
> 但在Safari中，即使报不安全，仍能打开：
> 
> <img alt="image" width="1424" src="https://private-user-images.githubusercontent.com/22313057/309741628-e07ac9f3-844b-4e26-a24c-97af46c79aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTMxMjIsIm5iZiI6MTcwOTU1MjgyMiwicGF0aCI6Ii8yMjMxMzA1Ny8zMDk3NDE2MjgtZTA3YWM5ZjMtODQ0Yi00ZTI2LWEyNGMtOTdhZjQ2Yzc5YWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTE4ZjNiYjFhMTU3NzlkNzg3YmYzZGRlOTU3YjI4YjI5Y2YyZWFlNmMzZmQxMzIxNWQ4YjM5Yzg2YjUyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrmfZeOHJiX_t7O57Y3VImz4k9I5eUn5N19HGaNu-CI">
> 是我这边有什么问题，还是谷歌又搞了什么妖蛾子？

删除数据后正常了。

**Comment by KyleBing** [comment]
以前是 https  现在改成了 http
