### ISSUE TITLE
不能自动重打

### ISSUE THREAD

**Issue by jzliming** [KyleBing/typepad#56]
![24ACDFE99440B7B604F22CBFA1D086C6](https://github.com/user-attachments/assets/bc515185-1f16-4c12-a7d8-05ec750e26e8)
打开了开关，重复当前 ，自动发文，打完就进入下一段了，不能重复当前的段，我记得以前是可以的。

**Comment by KyleBing** [comment]
有个次数设置




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月18日 09:27 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [KyleBing/typepad] 不能自动重打 (Issue #56) |

24ACDFE99440B7B604F22CBFA1D086C6.png (view on web)
打开了开关，重复当前 ，自动发文，打完就进入下一段了，不能重复当前的段，我记得以前是可以的。
