### ISSUE TITLE
能自定义发文吗?

### ISSUE THREAD

**Issue by bosconb** [KyleBing/typepad#6]
首先，谢谢作者为macOS上的五笔方案开发了诸多实用工具，一直苦于mac平台上没有好用的跟打器，偶尔发现了这个，很是惊喜。麻雀虽小，五脏俱全，自己看重的几个功能和MS主流跟打器相比也不逊色，而且更轻便直观。

不过我这里有个小问题：如果想自己发文跟打，除了在代码里更换外有没有好办法，今后的版本更新会不会增加自定义发文的功能？

再次感恩作者的付出！

**Comment by KyleBing** [comment]
多谢喜欢。
这个自定义文章的功能可以安排到之后，但恐怕会无限期延长。

因为这个工具初衷就是平时打字生疏的时候练练单字，其它只是陪衬。

之后可能会整个联网的文章吧，也不确定，毕竟感觉好像没有那么多时间整这个。无法保证。

**Comment by KyleBing** [comment]
已实现
